language: node_js

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - 4
  - 6
  - 8
  - lts/*
  - node

install:
  - yarn --ignore-engines

after_success:
  - ./node_modules/.bin/codecov

script: yarn test

branches:
  only:
    - master
    - default-props
